/*
 * obtain_neighbor_faces_mex.c
 *
 * Auxiliary code generation for function obtain_neighbor_faces
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "obtain_neighbor_faces.h"
#include "m2c.c"
#include "obtain_neighbor_faces.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void obtain_neighbor_faces_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     sibhes;
    emxArray_boolean_T   ftags;

    int32_T              fid;
    real_T               *ngbfaces;
    real_T               *nfaces;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces:WrongInputType",
            "Input argument fid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("obtain_neighbor_faces:WrongSizeOfInputArg",
            "Argument fid should be a scalar.");
    fid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces:WrongInputType",
            "Input argument sibhes has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&sibhes, "sibhes", 2);
    plhs[2] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[2]) && mxGetClassID(plhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces:WrongInputType",
            "Input argument ftags has incorrect data type. logical is expected.");
    alias_mxArray_to_emxArray(plhs[2], (emxArray__common *)&ftags, "ftags", 1);

    /* Preallocate output variables */
    {mwSize l_size[] = {100};
    *(void **)&ngbfaces = prealloc_mxArray((mxArray**)&plhs[0], mxDOUBLE_CLASS, 1, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&nfaces = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    obtain_neighbor_faces_initialize();
    obtain_neighbor_faces(fid, &sibhes, &ftags, ngbfaces, nfaces);
    obtain_neighbor_faces_terminate();
    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    if (ftags.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&ftags, mxLOGICAL_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&sibhes);
    free_emxArray( (emxArray__common*)&ftags);}

void obtain_neighbor_faces_usestruct_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_boolean_T   ftags;

    b_struct_T           sibhes;
    mxArray              *_sub_mx1;

    int32_T              fid;
    boolean_T            usestruct;
    real_T               *ngbfaces;
    real_T               *nfaces;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputType",
            "Input argument fid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongSizeOfInputArg",
            "Argument fid should be a scalar.");
    fid = *(int32_T*)mxGetData(prhs[0]);

    if ( !mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputType",
            "Input argument sibhes has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[1])!=2)
        mexWarnMsgIdAndTxt("obtain_neighbor_faces_usestruct:InputStructWrongFields",
            "Input argument sibhes has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongSizeOfInputArg",
            "Argument sibhes must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[1], 0, "fid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputStruct",
            "Input argument sibhes does not have the field fid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputType",
            "Input argument sibhes.fid has incorrect data type. int32 is expected.");
    *(void**)&sibhes.fid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)sibhes.fid, "sibhes.fid", 2);
    _sub_mx1 = mxGetField( prhs[1], 0, "leid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputStruct",
            "Input argument sibhes does not have the field leid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT8_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputType",
            "Input argument sibhes.leid has incorrect data type. int8 is expected.");
    *(void**)&sibhes.leid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)sibhes.leid, "sibhes.leid", 2);
    plhs[2] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[2]) && mxGetClassID(plhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputType",
            "Input argument ftags has incorrect data type. logical is expected.");
    alias_mxArray_to_emxArray(plhs[2], (emxArray__common *)&ftags, "ftags", 1);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongInputType",
            "Input argument usestruct has incorrect data type. logical is expected.");
    if ( mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:WrongSizeOfInputArg",
            "Argument usestruct should be a scalar.");
    usestruct = *(boolean_T*)mxGetData(prhs[3]);

    /* Preallocate output variables */
    {mwSize l_size[] = {100};
    *(void **)&ngbfaces = prealloc_mxArray((mxArray**)&plhs[0], mxDOUBLE_CLASS, 1, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&nfaces = prealloc_mxArray((mxArray**)&plhs[1], mxDOUBLE_CLASS, 2, l_size); }

    /* Invoke the target function */
    obtain_neighbor_faces_initialize();
    obtain_neighbor_faces_usestruct(fid, sibhes, &ftags, usestruct, ngbfaces, nfaces);
    obtain_neighbor_faces_terminate();
    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */
    if (ftags.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&ftags, mxLOGICAL_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)sibhes.leid); mxFree( sibhes.leid);
    free_emxArray( (emxArray__common*)sibhes.fid); mxFree( sibhes.fid);

    free_emxArray( (emxArray__common*)&ftags);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 3) {
         if (nlhs > 3)
            mexErrMsgIdAndTxt("obtain_neighbor_faces:TooManyOutputArguments","Too many output arguments for entry-point 'obtain_neighbor_faces'.");
        /* Call the API function. */
    obtain_neighbor_faces_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 4) {
         if (nlhs > 3)
            mexErrMsgIdAndTxt("obtain_neighbor_faces_usestruct:TooManyOutputArguments","Too many output arguments for entry-point 'obtain_neighbor_faces_usestruct'.");
        /* Call the API function. */
    obtain_neighbor_faces_usestruct_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("obtain_neighbor_faces:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'obtain_neighbor_faces'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}