/*
 * determine_sibling_halfverts_mex.c
 *
 * Auxiliary code generation for function determine_sibling_halfverts
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "determine_sibling_halfverts.h"
#include "m2c.c"
#include "determine_sibling_halfverts.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void determine_sibling_halfverts_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edges;
    emxArray_int32_T     sibhvs;

    int32_T              nv;
    boolean_T            *manifold;
    boolean_T            *oriented;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfverts:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_sibling_halfverts:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfverts:WrongInputType",
            "Input argument edges has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edges, "edges", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&sibhvs, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&manifold = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&oriented = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    determine_sibling_halfverts_initialize();
    determine_sibling_halfverts(nv, &edges, &sibhvs, manifold, oriented);
    determine_sibling_halfverts_terminate();
    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&sibhvs, mxINT32_CLASS);
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edges);
    free_emxArray( (emxArray__common*)&sibhvs);}

void determine_sibling_halfverts_usestruct_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edges;

    struct_T             sibhvs;
    mxArray              *_sub_mx1;

    int32_T              nv;
    boolean_T            usestruct;
    boolean_T            *manifold;
    boolean_T            *oriented;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfverts_usestruct:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_sibling_halfverts_usestruct:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfverts_usestruct:WrongInputType",
            "Input argument edges has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edges, "edges", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfverts_usestruct:WrongInputType",
            "Input argument usestruct has incorrect data type. logical is expected.");
    if ( mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("determine_sibling_halfverts_usestruct:WrongSizeOfInputArg",
            "Argument usestruct should be a scalar.");
    usestruct = *(boolean_T*)mxGetData(prhs[2]);

    /* Preallocate output variables */
    *(void **)&sibhvs.eid = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)sibhvs.eid, 2);
    *(void **)&sibhvs.lvid = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)sibhvs.lvid, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&manifold = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&oriented = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    determine_sibling_halfverts_initialize();
    determine_sibling_halfverts_usestruct(nv, &edges, usestruct, &sibhvs, manifold, oriented);
    determine_sibling_halfverts_terminate();
    /* Marshall out function outputs */
    {const char *_fields[] = { "eid", "lvid",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray( 1, &_one, 2, _fields);}
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)sibhvs.eid, mxINT32_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)sibhvs.lvid, mxINT8_CLASS));
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edges);
    free_emxArray( (emxArray__common*)sibhvs.lvid); mxFree( sibhvs.lvid);
    free_emxArray( (emxArray__common*)sibhvs.eid); mxFree( sibhvs.eid);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 2) {
         if (nlhs > 3)
            mexErrMsgIdAndTxt("determine_sibling_halfverts:TooManyOutputArguments","Too many output arguments for entry-point 'determine_sibling_halfverts'.");
        /* Call the API function. */
    determine_sibling_halfverts_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 3) {
         if (nlhs > 3)
            mexErrMsgIdAndTxt("determine_sibling_halfverts_usestruct:TooManyOutputArguments","Too many output arguments for entry-point 'determine_sibling_halfverts_usestruct'.");
        /* Call the API function. */
    determine_sibling_halfverts_usestruct_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("determine_sibling_halfverts:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'determine_sibling_halfverts'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}