/*
 * eid2adj_edges_mex.c
 *
 * Auxiliary code generation for function eid2adj_edges
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "eid2adj_edges.h"
#include "m2c.c"
#include "eid2adj_edges.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void eid2adj_edges_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edges;
    emxArray_int32_T     v2hv;
    emxArray_int32_T     sibhvs;
    emxArray_int32_T     edge_list;

    int32_T              eid;
    real_T               nedges;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_edges:WrongInputType",
            "Input argument eid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("eid2adj_edges:WrongSizeOfInputArg",
            "Argument eid should be a scalar.");
    eid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_edges:WrongInputType",
            "Input argument edges has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edges, "edges", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_edges:WrongInputType",
            "Input argument v2hv has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&v2hv, "v2hv", 1);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_edges:WrongInputType",
            "Input argument sibhvs has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&sibhvs, "sibhvs", 2);
    plhs[0] = mxDuplicateArray( prhs[4]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_edges:WrongInputType",
            "Input argument edge_list has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&edge_list, "edge_list", 1);

    /* Preallocate output variables */

    /* Invoke the target function */
    eid2adj_edges_initialize();
    nedges = eid2adj_edges(eid, &edges, &v2hv, &sibhvs, &edge_list);
    eid2adj_edges_terminate();
    /* Marshall out function outputs */
    if (edge_list.canFreeData) plhs[4] = move_emxArray_to_mxArray((emxArray__common*)&edge_list, mxINT32_CLASS);
    plhs[1] = copy_scalar_to_mxArray(&nedges, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edges);
    free_emxArray( (emxArray__common*)&v2hv);
    free_emxArray( (emxArray__common*)&sibhvs);
    free_emxArray( (emxArray__common*)&edge_list);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 5) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("eid2adj_edges:TooManyOutputArguments","Too many output arguments for entry-point 'eid2adj_edges'.");
        /* Call the API function. */
    eid2adj_edges_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("eid2adj_edges:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'eid2adj_edges'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}