function [ngbes, nelems, etags] = obtain_1ring_elems_tet_usestruct( vid, ...
    tets, sibhfs, v2hf, ngbes, etags, usestruct)
[ngbes, nelems, etags] = obtain_1ring_elems_tet( vid, ...
    tets, sibhfs, v2hf, ngbes, etags, usestruct);