/*
 * obtain_1ring_curv_NM_mex.c
 *
 * Auxiliary code generation for function obtain_1ring_curv_NM
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "obtain_1ring_curv_NM.h"
#include "m2c.c"
#include "obtain_1ring_curv_NM.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void obtain_1ring_curv_NM_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edges;
    emxArray_int32_T     sibhvs;
    emxArray_int32_T     v2hv;

    int32_T              vid;
    int32_T              *ngbvs;
    int32_T              *nverts;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM:WrongInputType",
            "Input argument vid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM:WrongSizeOfInputArg",
            "Argument vid should be a scalar.");
    vid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM:WrongInputType",
            "Input argument edges has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edges, "edges", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM:WrongInputType",
            "Input argument sibhvs has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&sibhvs, "sibhvs", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM:WrongInputType",
            "Input argument v2hv has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&v2hv, "v2hv", 1);

    /* Preallocate output variables */
    {mwSize l_size[] = {10};
    *(void **)&ngbvs = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 1, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&nverts = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    obtain_1ring_curv_NM_initialize();
    obtain_1ring_curv_NM(vid, &edges, &sibhvs, &v2hv, ngbvs, nverts);
    obtain_1ring_curv_NM_terminate();
    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edges);
    free_emxArray( (emxArray__common*)&sibhvs);
    free_emxArray( (emxArray__common*)&v2hv);}

void obtain_1ring_curv_NM_usestruct_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edges;

    struct_T             sibhvs;
    struct_T             v2hv;
    mxArray              *_sub_mx1;

    int32_T              vid;
    boolean_T            usestruct;
    int32_T              *ngbvs;
    int32_T              *nverts;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument vid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongSizeOfInputArg",
            "Argument vid should be a scalar.");
    vid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument edges has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edges, "edges", 2);

    if ( !mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument sibhvs has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[2])!=2)
        mexWarnMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:InputStructWrongFields",
            "Input argument sibhvs has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongSizeOfInputArg",
            "Argument sibhvs must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[2], 0, "eid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputStruct",
            "Input argument sibhvs does not have the field eid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument sibhvs.eid has incorrect data type. int32 is expected.");
    *(void**)&sibhvs.eid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)sibhvs.eid, "sibhvs.eid", 2);
    _sub_mx1 = mxGetField( prhs[2], 0, "lvid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputStruct",
            "Input argument sibhvs does not have the field lvid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT8_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument sibhvs.lvid has incorrect data type. int8 is expected.");
    *(void**)&sibhvs.lvid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)sibhvs.lvid, "sibhvs.lvid", 2);

    if ( !mxIsStruct(prhs[3]))
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument v2hv has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[3])!=2)
        mexWarnMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:InputStructWrongFields",
            "Input argument v2hv has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongSizeOfInputArg",
            "Argument v2hv must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[3], 0, "eid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputStruct",
            "Input argument v2hv does not have the field eid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument v2hv.eid has incorrect data type. int32 is expected.");
    *(void**)&v2hv.eid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)v2hv.eid, "v2hv.eid", 1);
    _sub_mx1 = mxGetField( prhs[3], 0, "lvid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputStruct",
            "Input argument v2hv does not have the field lvid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT8_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument v2hv.lvid has incorrect data type. int8 is expected.");
    *(void**)&v2hv.lvid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)v2hv.lvid, "v2hv.lvid", 1);
    if ( mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongInputType",
            "Input argument usestruct has incorrect data type. logical is expected.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:WrongSizeOfInputArg",
            "Argument usestruct should be a scalar.");
    usestruct = *(boolean_T*)mxGetData(prhs[4]);

    /* Preallocate output variables */
    {mwSize l_size[] = {10};
    *(void **)&ngbvs = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 1, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&nverts = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    obtain_1ring_curv_NM_initialize();
    obtain_1ring_curv_NM_usestruct(vid, &edges, sibhvs, v2hv, usestruct, ngbvs, nverts);
    obtain_1ring_curv_NM_terminate();
    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edges);
    free_emxArray( (emxArray__common*)sibhvs.lvid); mxFree( sibhvs.lvid);
    free_emxArray( (emxArray__common*)sibhvs.eid); mxFree( sibhvs.eid);

    free_emxArray( (emxArray__common*)v2hv.lvid); mxFree( v2hv.lvid);
    free_emxArray( (emxArray__common*)v2hv.eid); mxFree( v2hv.eid);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 4) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("obtain_1ring_curv_NM:TooManyOutputArguments","Too many output arguments for entry-point 'obtain_1ring_curv_NM'.");
        /* Call the API function. */
    obtain_1ring_curv_NM_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 5) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("obtain_1ring_curv_NM_usestruct:TooManyOutputArguments","Too many output arguments for entry-point 'obtain_1ring_curv_NM_usestruct'.");
        /* Call the API function. */
    obtain_1ring_curv_NM_usestruct_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("obtain_1ring_curv_NM:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'obtain_1ring_curv_NM'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}