function [ngbvs, nverts, vtags, ftags, ngbfs, nfaces] = obtain_1ring_surf_nmanfld_usestruct...
    ( vid, tris, sibhes, v2he, vtags, ftags, usestruct)
[ngbvs, nverts, vtags, ftags, ngbfs, nfaces] = obtain_1ring_surf_nmanfld...
    ( vid, tris, sibhes, v2he, vtags, ftags, usestruct);
