/*
 * determine_sibling_halfedges_mex.c
 *
 * Auxiliary code generation for function determine_sibling_halfedges
 *
 * C source code generated by lib2mex on: 15-Apr-2013 00:46:15
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "determine_sibling_halfedges.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


void determine_sibling_halfedges_api(const mxArray * prhs[2], const mxArray *plhs[3]) {

    emxArray_int32_T     elems;
    emxArray_int32_T     sibhes;


    int32_T              nv;
    boolean_T            *manifold;
    boolean_T            *oriented;

    /* Marshall in function inputs */
    if ( mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfedges:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_sibling_halfedges:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_sibling_halfedges:WrongInputType",
            "Input argument elems has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&elems, "elems", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&sibhes, 2);
    {mwSize l_size[] = {1, 1};
    manifold = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    oriented = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    determine_sibling_halfedges_initialize();
    determine_sibling_halfedges(nv, &elems, &sibhes, manifold, oriented);
    determine_sibling_halfedges_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&sibhes, mxINT32_CLASS);
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&elems);
    free_emxArray( (emxArray__common*)&sibhes);
}

