/*
 * eid2adj_faces_mex.c
 *
 * Auxiliary code generation for function eid2adj_faces
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "eid2adj_faces.h"
#include "m2c.c"
#include "eid2adj_faces.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void eid2adj_faces_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edges;
    emxArray_int32_T     tris;
    emxArray_int32_T     v2he;
    emxArray_int32_T     sibhes;
    emxArray_int32_T     flist;
    emxArray_boolean_T   ftags;

    int32_T              eid;
    real_T               nfaces;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument eid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongSizeOfInputArg",
            "Argument eid should be a scalar.");
    eid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument edges has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edges, "edges", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument tris has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&tris, "tris", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument v2he has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&v2he, "v2he", 1);
    if ( mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument sibhes has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[4], (emxArray__common *)&sibhes, "sibhes", 2);
    plhs[0] = mxDuplicateArray( prhs[5]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument flist has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&flist, "flist", 1);
    plhs[2] = mxDuplicateArray( prhs[6]);
    if ( mxGetNumberOfElements(plhs[2]) && mxGetClassID(plhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("eid2adj_faces:WrongInputType",
            "Input argument ftags has incorrect data type. logical is expected.");
    alias_mxArray_to_emxArray(plhs[2], (emxArray__common *)&ftags, "ftags", 1);

    /* Preallocate output variables */

    /* Invoke the target function */
    eid2adj_faces_initialize();
    nfaces = eid2adj_faces(eid, &edges, &tris, &v2he, &sibhes, &flist, &ftags);
    eid2adj_faces_terminate();
    /* Marshall out function outputs */
    if (flist.canFreeData) plhs[5] = move_emxArray_to_mxArray((emxArray__common*)&flist, mxINT32_CLASS);
    plhs[1] = copy_scalar_to_mxArray(&nfaces, mxDOUBLE_CLASS);
    if (ftags.canFreeData) plhs[6] = move_emxArray_to_mxArray((emxArray__common*)&ftags, mxLOGICAL_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edges);
    free_emxArray( (emxArray__common*)&tris);
    free_emxArray( (emxArray__common*)&v2he);
    free_emxArray( (emxArray__common*)&sibhes);
    free_emxArray( (emxArray__common*)&flist);
    free_emxArray( (emxArray__common*)&ftags);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 7) {
         if (nlhs > 3)
            mexErrMsgIdAndTxt("eid2adj_faces:TooManyOutputArguments","Too many output arguments for entry-point 'eid2adj_faces'.");
        /* Call the API function. */
    eid2adj_faces_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("eid2adj_faces:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'eid2adj_faces'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}