/*
 * determine_incident_halfedges_mex.c
 *
 * Auxiliary code generation for function determine_incident_halfedges
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "determine_incident_halfedges.h"
#include "m2c.c"
#include "determine_incident_halfedges.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void determine_incident_halfedges_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     elems;
    emxArray_int32_T     sibhes;
    emxArray_int32_T     v2he;

    int32_T              nv;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfedges:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges:WrongInputType",
            "Input argument elems has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&elems, "elems", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges:WrongInputType",
            "Input argument sibhes has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&sibhes, "sibhes", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&v2he, 1);

    /* Invoke the target function */
    determine_incident_halfedges_initialize();
    determine_incident_halfedges(nv, &elems, &sibhes, &v2he);
    determine_incident_halfedges_terminate();
    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&v2he, mxINT32_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&elems);
    free_emxArray( (emxArray__common*)&sibhes);
    free_emxArray( (emxArray__common*)&v2he);}

void determine_incident_halfedges_usestruct_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     elems;

    struct_T             sibhes;
    struct_T             v2he;
    mxArray              *_sub_mx1;

    int32_T              nv;
    boolean_T            usestruct;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputType",
            "Input argument elems has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&elems, "elems", 2);

    if ( !mxIsStruct(prhs[2]))
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputType",
            "Input argument sibhes has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[2])!=2)
        mexWarnMsgIdAndTxt("determine_incident_halfedges_usestruct:InputStructWrongFields",
            "Input argument sibhes has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongSizeOfInputArg",
            "Argument sibhes must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[2], 0, "fid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputStruct",
            "Input argument sibhes does not have the field fid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputType",
            "Input argument sibhes.fid has incorrect data type. int32 is expected.");
    *(void**)&sibhes.fid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)sibhes.fid, "sibhes.fid", 2);
    _sub_mx1 = mxGetField( prhs[2], 0, "leid");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputStruct",
            "Input argument sibhes does not have the field leid.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT8_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputType",
            "Input argument sibhes.leid has incorrect data type. int8 is expected.");
    *(void**)&sibhes.leid = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)sibhes.leid, "sibhes.leid", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongInputType",
            "Input argument usestruct has incorrect data type. logical is expected.");
    if ( mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:WrongSizeOfInputArg",
            "Argument usestruct should be a scalar.");
    usestruct = *(boolean_T*)mxGetData(prhs[3]);

    /* Preallocate output variables */
    *(void **)&v2he.fid = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)v2he.fid, 1);
    *(void **)&v2he.leid = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)v2he.leid, 1);

    /* Invoke the target function */
    determine_incident_halfedges_initialize();
    determine_incident_halfedges_usestruct(nv, &elems, sibhes, usestruct, &v2he);
    determine_incident_halfedges_terminate();
    /* Marshall out function outputs */
    {const char *_fields[] = { "fid", "leid",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray( 1, &_one, 2, _fields);}
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)v2he.fid, mxINT32_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)v2he.leid, mxINT8_CLASS));    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&elems);
    free_emxArray( (emxArray__common*)sibhes.leid); mxFree( sibhes.leid);
    free_emxArray( (emxArray__common*)sibhes.fid); mxFree( sibhes.fid);

    free_emxArray( (emxArray__common*)v2he.leid); mxFree( v2he.leid);
    free_emxArray( (emxArray__common*)v2he.fid); mxFree( v2he.fid);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 3) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("determine_incident_halfedges:TooManyOutputArguments","Too many output arguments for entry-point 'determine_incident_halfedges'.");
        /* Call the API function. */
        determine_incident_halfedges_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 4) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("determine_incident_halfedges_usestruct:TooManyOutputArguments","Too many output arguments for entry-point 'determine_incident_halfedges_usestruct'.");
        /* Call the API function. */
        determine_incident_halfedges_usestruct_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("determine_incident_halfedges:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'determine_incident_halfedges'.");
}