function build

compile is_quadmesh
compile is_2dmesh
compile determine_border_vertices
m2mex determine_border_vertices_vol
m2mex determine_opposite_halfface
compile extract_border_surf

compile nnz_elements
compile split_mixed_elems
compile determine_offsets_mixed_elems
compile linearize_mixed_elems
compile regularize_mixed_elems
compile merge_mixed_elems
