/*
 * obtain_1ring_surf_nmanfld_mex.c
 *
 * Auxiliary code generation for function obtain_1ring_surf_nmanfld
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "obtain_1ring_surf_nmanfld.h"
#include "m2c.c"
#include "obtain_1ring_surf_nmanfld.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void obtain_1ring_surf_nmanfld_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     tris;
    emxArray_int32_T     sibhes;
    emxArray_int32_T     v2he;
    emxArray_boolean_T   vtags;
    emxArray_boolean_T   ftags;
    emxArray_int32_T     ngbvs;
    emxArray_int32_T     ngbfs;

    int32_T              vid;
    int32_T              *nverts;
    int32_T              *nfaces;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongInputType",
            "Input argument vid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongSizeOfInputArg",
            "Argument vid should be a scalar.");
    vid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongInputType",
            "Input argument tris has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&tris, "tris", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongInputType",
            "Input argument sibhes has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&sibhes, "sibhes", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongInputType",
            "Input argument v2he has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&v2he, "v2he", 1);
    plhs[2] = mxDuplicateArray( prhs[4]);
    if ( mxGetNumberOfElements(plhs[2]) && mxGetClassID(plhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongInputType",
            "Input argument vtags has incorrect data type. logical is expected.");
    alias_mxArray_to_emxArray(plhs[2], (emxArray__common *)&vtags, "vtags", 1);
    plhs[3] = mxDuplicateArray( prhs[5]);
    if ( mxGetNumberOfElements(plhs[3]) && mxGetClassID(plhs[3]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongInputType",
            "Input argument ftags has incorrect data type. logical is expected.");
    alias_mxArray_to_emxArray(plhs[3], (emxArray__common *)&ftags, "ftags", 1);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&ngbvs, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&nverts = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    init_emxArray((emxArray__common*)&ngbfs, 1);
    {mwSize l_size[] = {1, 1};
    *(void **)&nfaces = prealloc_mxArray((mxArray**)&plhs[5], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    obtain_1ring_surf_nmanfld_initialize();
    obtain_1ring_surf_nmanfld(vid, &tris, &sibhes, &v2he, &vtags, &ftags, &ngbvs, nverts, &ngbfs, nfaces);
    obtain_1ring_surf_nmanfld_terminate();
    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&ngbvs, mxINT32_CLASS);
    /* Nothing to do for plhs[1] */
    if (vtags.canFreeData) plhs[4] = move_emxArray_to_mxArray((emxArray__common*)&vtags, mxLOGICAL_CLASS);
    if (ftags.canFreeData) plhs[5] = move_emxArray_to_mxArray((emxArray__common*)&ftags, mxLOGICAL_CLASS);
    plhs[4] = move_emxArray_to_mxArray((emxArray__common*)&ngbfs, mxINT32_CLASS);
    /* Nothing to do for plhs[5] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&tris);
    free_emxArray( (emxArray__common*)&sibhes);
    free_emxArray( (emxArray__common*)&v2he);
    free_emxArray( (emxArray__common*)&vtags);
    free_emxArray( (emxArray__common*)&ftags);
    free_emxArray( (emxArray__common*)&ngbvs);
    free_emxArray( (emxArray__common*)&ngbfs);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[6];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 6) {
         if (nlhs > 6)
            mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:TooManyOutputArguments","Too many output arguments for entry-point 'obtain_1ring_surf_nmanfld'.");
        /* Call the API function. */
    obtain_1ring_surf_nmanfld_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("obtain_1ring_surf_nmanfld:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'obtain_1ring_surf_nmanfld'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}