/*
 * determine_incident_halfverts_mex.c
 *
 * Auxiliary code generation for function determine_incident_halfverts
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "determine_incident_halfverts.h"
#include "m2c.c"
#include "determine_incident_halfverts.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void determine_incident_halfverts_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edgs;
    emxArray_int32_T     v2hv;

    int32_T              nv;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfverts:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfverts:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfverts:WrongInputType",
            "Input argument edgs has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edgs, "edgs", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&v2hv, 1);

    /* Invoke the target function */
    determine_incident_halfverts_initialize();
    determine_incident_halfverts(nv, &edgs, &v2hv);
    determine_incident_halfverts_terminate();
    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&v2hv, mxINT32_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edgs);
    free_emxArray( (emxArray__common*)&v2hv);}

void determine_incident_halfverts_usestruct_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     edgs;

    struct_T             v2hv;
    mxArray              *_sub_mx1;

    int32_T              nv;
    boolean_T            usestruct;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfverts_usestruct:WrongInputType",
            "Input argument nv has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfverts_usestruct:WrongSizeOfInputArg",
            "Argument nv should be a scalar.");
    nv = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfverts_usestruct:WrongInputType",
            "Input argument edgs has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&edgs, "edgs", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("determine_incident_halfverts_usestruct:WrongInputType",
            "Input argument usestruct has incorrect data type. logical is expected.");
    if ( mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("determine_incident_halfverts_usestruct:WrongSizeOfInputArg",
            "Argument usestruct should be a scalar.");
    usestruct = *(boolean_T*)mxGetData(prhs[2]);

    /* Preallocate output variables */
    *(void **)&v2hv.eid = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)v2hv.eid, 1);
    *(void **)&v2hv.lvid = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)v2hv.lvid, 1);

    /* Invoke the target function */
    determine_incident_halfverts_initialize();
    determine_incident_halfverts_usestruct(nv, &edgs, usestruct, &v2hv);
    determine_incident_halfverts_terminate();
    /* Marshall out function outputs */
    {const char *_fields[] = { "eid", "lvid",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray( 1, &_one, 2, _fields);}
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)v2hv.eid, mxINT32_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)v2hv.lvid, mxINT8_CLASS));    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&edgs);
    free_emxArray( (emxArray__common*)v2hv.lvid); mxFree( v2hv.lvid);
    free_emxArray( (emxArray__common*)v2hv.eid); mxFree( v2hv.eid);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 2) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("determine_incident_halfverts:TooManyOutputArguments","Too many output arguments for entry-point 'determine_incident_halfverts'.");
        /* Call the API function. */
        determine_incident_halfverts_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 3) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("determine_incident_halfverts_usestruct:TooManyOutputArguments","Too many output arguments for entry-point 'determine_incident_halfverts_usestruct'.");
        /* Call the API function. */
        determine_incident_halfverts_usestruct_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("determine_incident_halfverts:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'determine_incident_halfverts'.");
}