/*
 * obtain_1ring_elems_tet_mex.c
 *
 * Auxiliary code generation for function obtain_1ring_elems_tet
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "obtain_1ring_elems_tet.h"
#include "m2c.c"
#include "obtain_1ring_elems_tet.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void obtain_1ring_elems_tet_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_int32_T     tets;
    emxArray_int32_T     sibhfs;
    emxArray_int32_T     v2hf;
    emxArray_int32_T     ngbes;
    emxArray_boolean_T   etags;

    int32_T              vid;
    int32_T              nelems;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongInputType",
            "Input argument vid has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongSizeOfInputArg",
            "Argument vid should be a scalar.");
    vid = *(int32_T*)mxGetData(prhs[0]);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongInputType",
            "Input argument tets has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&tets, "tets", 2);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongInputType",
            "Input argument sibhfs has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&sibhfs, "sibhfs", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongInputType",
            "Input argument v2hf has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&v2hf, "v2hf", 1);
    plhs[0] = mxDuplicateArray( prhs[4]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongInputType",
            "Input argument ngbes has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&ngbes, "ngbes", 1);
    plhs[2] = mxDuplicateArray( prhs[5]);
    if ( mxGetNumberOfElements(plhs[2]) && mxGetClassID(plhs[2]) != mxLOGICAL_CLASS)
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongInputType",
            "Input argument etags has incorrect data type. logical is expected.");
    alias_mxArray_to_emxArray(plhs[2], (emxArray__common *)&etags, "etags", 1);

    /* Preallocate output variables */

    /* Invoke the target function */
    obtain_1ring_elems_tet_initialize();
    nelems = obtain_1ring_elems_tet(vid, &tets, &sibhfs, &v2hf, &ngbes, &etags);
    obtain_1ring_elems_tet_terminate();
    /* Marshall out function outputs */
    if (ngbes.canFreeData) plhs[4] = move_emxArray_to_mxArray((emxArray__common*)&ngbes, mxINT32_CLASS);
    plhs[1] = copy_scalar_to_mxArray(&nelems, mxINT32_CLASS);
    if (etags.canFreeData) plhs[5] = move_emxArray_to_mxArray((emxArray__common*)&etags, mxLOGICAL_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&tets);
    free_emxArray( (emxArray__common*)&sibhfs);
    free_emxArray( (emxArray__common*)&v2hf);
    free_emxArray( (emxArray__common*)&ngbes);
    free_emxArray( (emxArray__common*)&etags);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 6) {
         if (nlhs > 3)
            mexErrMsgIdAndTxt("obtain_1ring_elems_tet:TooManyOutputArguments","Too many output arguments for entry-point 'obtain_1ring_elems_tet'.");
        /* Call the API function. */
    obtain_1ring_elems_tet_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("obtain_1ring_elems_tet:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'obtain_1ring_elems_tet'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}