/*
 * determine_sibling_halffaces_prism_mex.c
 *
 * Auxiliary code generation for function determine_sibling_halffaces_prism
 *
 * C source code generated by lib2mex on: 08-Apr-2013 14:06:35
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "determine_sibling_halffaces_prism.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

