function [ngbvs, nverts] = obtain_1ring_curv_NM_usestruct...
    ( vid, edges, sibhvs, v2hv, usestruct) %#codegen
[ngbvs, nverts] = obtain_1ring_curv_NM...
    ( vid, edges, sibhvs, v2hv, usestruct);